Partial implementation of the CTS XML property file functionality
This attempts to replace the simple properties file implementation
with a full XML implementation.

This is not working: I think the issue is with XML validation.

ApplicationBean.java, line 376:

javax.xml.bind.UnmarshalException: unexpected element (uri:"http://schema.samply.de/common", local:"cts"). Expected elements are <{http://schema.samply.de/config/BridgeheadInfo}bridgehead>,<{http://schema.samply.de/common}operator>,<{http://schema.samply.de/common}urls>

I have created a new XSD file in "xsd/common_cts_info.xsd", but
JAX isn't finding it, so I guess there is a missing setup step
somewhere.